### ISSUE TITLE
Colour theme broken with latest Jetbrains Rider Nightly build

### ISSUE THREAD

**Issue by mchataway** [rmehri01/onenord-jetbrains#12]
After updating Rider to the latest Nightly build, the colour scheme has broken.
The background went completely white and all colours seem wrong.

**Comment by rmehri01** [comment]
Hey there! 

I think this happened to me too, can you go to `Settings` > `Editor` > `Color Scheme` and see if it got set to the Classic Light editor theme instead of OneNord? 

I don't think this is an issue with the plugin since I don't think there is anything related to the light theme and other themes seem to get unloaded as well when updating but I can ask about it in the JetBrains slack just in case. 🙂

**Comment by mchataway** [comment]
Heya thanks for the super quick reply :)

When I go to `Settings `> `Editor `> `Color Scheme` in my case it does indeed seem to not be set to OneNord even once I switch the overall theme to OneNord, but it seems to stay on whichever theme I had it set to before switching.
If I click the reset button in the upper right it does go back to Classic Light, but then when I change it to OneNord it doesn't change the colours at all, and everything is still set to a bright theme (probably Classic Light).

All the other themes I have installed seem to be working correctly.
I'm also using Material UI theme, do you think that could be causing any issues with it?

**Comment by rmehri01** [comment]
No problem! I'll ask about it anyways because this is something I've been meaning to get to for a while, I'm not sure why it unloads the chosen theme when it's updated.
