### ISSUE TITLE
Undercurl for diagnostics

### ISSUE THREAD

**Issue by fikovnik** [rmehri01/onenord-jetbrains#5]
This is a great theme, but I was wondering if it would be possible to use undercurl for diagnostics. Currently, the solid line makes it somewhat harder to read.

**Comment by rmehri01** [comment]
Thanks, I'm glad you like it! 😄 

Sure, that is doable. I was basing it off of what is done in the IntelliJ New Dark theme but I can see how it can be a bit hard to read since the line is bolded: 

<img width="405" alt="Screenshot 2023-02-24 at 6 45 50 PM" src="https://user-images.githubusercontent.com/52933714/221332280-a36460b1-7aee-4eae-bb12-6f12441d0d01.png">

This does seem quite a bit nicer:

<img width="265" alt="Screenshot 2023-02-24 at 6 51 10 PM" src="https://user-images.githubusercontent.com/52933714/221332457-ec87fcd5-dcaf-44ce-93b3-00663811ca23.png">

**Comment by fikovnik** [comment]
Thanks a lot for a quick fix! Is it possible to release to Jetbrains marketplace?

**Comment by rmehri01** [comment]
Already done, it should be up now, it was just awaiting approval!

**Comment by fikovnik** [comment]
Thank you!
